#!/usr/bin/env bash
# Why you no love me?

echo $$ >/var/run/myscript.pid

trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid && exit 0" SIGQUIT
trap "echo 'I hate the kill command' ;
	  rm -rf /var/run/myscript.pid ;
	  exit 0" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
