#!/usr/bin/env bash
# This bash script displays `To infinity and beyond` indefinitely with a
# `sleep 2` in between each iteration, and when a SIGTERM signal is sent it
# displays `I am invincible!!!`
trap "echo 'I am invincible!!!'" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
