#!/usr/bin/env bash
# The problem with the container was that apache2 was installed but it wasn't
# running yet, so we need to start the apache service and make it return the
# string 'Hello Holberton'
echo "ServerName localhost" >>/etc/apache2/apache2.conf
sudo service apache2 start
echo "Hello Holberton" >/var/www/html/index.html
